server:
  port: 8002
  servlet:
    context-path: /catalog/

spring:
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://eurekaserver:8761/eureka}
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq3
    port: 5672

queue:
  movie:
    name: MovieQueue

mensagem: hello catalog

management:
  endpoints:
    web:
      exposure:
        include: '*'
