server:
  port: 9411
 

spring:
  eureka:
    client:
      region: default
      registryFetchIntervalSeconds: 5
      serviceUrl:
        defaultZone: http://eurekaserver:8761/eureka
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      password: 123456
      name: zipkin2
      username: zipkinuser

